import "./globals.css";

import Header from "./Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className="min-h-screen h-full flex flex-col">
        <Header />
        {children}
        <footer className="w-screen flex justify-center items-center p-2 bg-red-100 mt-auto">
          난 푸터야
        </footer>
      </body>
    </html>
  );
}
